
import { useState } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ja' | 'ko' | 'zh';

const translations = {
  en: {
    back: 'Back',
    traveler: 'traveler',
    travelers: 'travelers',
    timeZone: 'Time Zone',
    yourTime: 'Your Time',
    currency: 'Currency',
    liveRate: 'Live rate',
    airport: 'Airport',
    primaryAirport: 'Primary Airport',
    distance: 'Distance',
    travelTime: 'Travel Time',
    options: 'Options',
    variable: 'Variable',
    multipleOptions: 'Multiple options',
    visaEntry: 'Visa & Entry',
    visaFreeEntry: 'Visa-free entry',
    forUSPassport: 'For US passport holders',
    maxStay: 'Max stay',
    days: 'days',
    passportValidity: 'Passport validity',
    monthsMin: 'months min',
    yellowFever: 'Yellow fever',
    vaccinationRecommended: 'Vaccination recommended',
    viewRequirements: 'View Requirements',
    weatherIntel: 'Weather Intel',
    transport: 'Transport',
    rental: 'Rental',
    public: 'Public',
    taxi: 'Taxi',
    avgCarRental: 'Avg car rental',
    day: 'day',
    gasPrice: 'Gas price',
    publicTransport: 'Public transport',
    holidays: 'Holidays',
    noUpcomingHolidays: 'No upcoming holidays found',
    accommodationMap: 'Accommodation Map'
  },
  es: {
    back: 'Atrás',
    traveler: 'viajero',
    travelers: 'viajeros',
    timeZone: 'Zona Horaria',
    yourTime: 'Tu Hora',
    currency: 'Moneda',
    liveRate: 'Tasa en vivo',
    airport: 'Aeropuerto',
    primaryAirport: 'Aeropuerto Principal',
    distance: 'Distancia',
    travelTime: 'Tiempo de Viaje',
    options: 'Opciones',
    variable: 'Variable',
    multipleOptions: 'Múltiples opciones',
    visaEntry: 'Visa y Entrada',
    visaFreeEntry: 'Entrada sin visa',
    forUSPassport: 'Para portadores de pasaporte estadounidense',
    maxStay: 'Estancia máxima',
    days: 'días',
    passportValidity: 'Validez del pasaporte',
    monthsMin: 'meses mín',
    yellowFever: 'Fiebre amarilla',
    vaccinationRecommended: 'Vacunación recomendada',
    viewRequirements: 'Ver Requisitos',
    weatherIntel: 'Intel del Clima',
    transport: 'Transporte',
    rental: 'Alquiler',
    public: 'Público',
    taxi: 'Taxi',
    avgCarRental: 'Alquiler promedio de auto',
    day: 'día',
    gasPrice: 'Precio de gasolina',
    publicTransport: 'Transporte público',
    holidays: 'Feriados',
    noUpcomingHolidays: 'No se encontraron feriados próximos',
    accommodationMap: 'Mapa de Alojamiento'
  },
  fr: {
    back: 'Retour',
    traveler: 'voyageur',
    travelers: 'voyageurs',
    timeZone: 'Fuseau Horaire',
    yourTime: 'Votre Heure',
    currency: 'Devise',
    liveRate: 'Taux en direct',
    airport: 'Aéroport',
    primaryAirport: 'Aéroport Principal',
    distance: 'Distance',
    travelTime: 'Temps de Voyage',
    options: 'Options',
    variable: 'Variable',
    multipleOptions: 'Plusieurs options',
    visaEntry: 'Visa et Entrée',
    visaFreeEntry: 'Entrée sans visa',
    forUSPassport: 'Pour les détenteurs de passeport américain',
    maxStay: 'Séjour maximum',
    days: 'jours',
    passportValidity: 'Validité du passeport',
    monthsMin: 'mois min',
    yellowFever: 'Fièvre jaune',
    vaccinationRecommended: 'Vaccination recommandée',
    viewRequirements: 'Voir les Exigences',
    weatherIntel: 'Intel Météo',
    transport: 'Transport',
    rental: 'Location',
    public: 'Public',
    taxi: 'Taxi',
    avgCarRental: 'Location de voiture moyenne',
    day: 'jour',
    gasPrice: 'Prix de l\'essence',
    publicTransport: 'Transport public',
    holidays: 'Jours Fériés',
    noUpcomingHolidays: 'Aucun jour férié à venir trouvé',
    accommodationMap: 'Carte d\'Hébergement'
  },
  de: {
    back: 'Zurück',
    traveler: 'Reisender',
    travelers: 'Reisende',
    timeZone: 'Zeitzone',
    yourTime: 'Ihre Zeit',
    currency: 'Währung',
    liveRate: 'Live-Kurs',
    airport: 'Flughafen',
    primaryAirport: 'Hauptflughafen',
    distance: 'Entfernung',
    travelTime: 'Reisezeit',
    options: 'Optionen',
    variable: 'Variabel',
    multipleOptions: 'Mehrere Optionen',
    visaEntry: 'Visa & Einreise',
    visaFreeEntry: 'Visafreie Einreise',
    forUSPassport: 'Für US-Passinhaber',
    maxStay: 'Max. Aufenthalt',
    days: 'Tage',
    passportValidity: 'Passgültigkeit',
    monthsMin: 'Monate min',
    yellowFever: 'Gelbfieber',
    vaccinationRecommended: 'Impfung empfohlen',
    viewRequirements: 'Anforderungen Anzeigen',
    weatherIntel: 'Wetter Intel',
    transport: 'Transport',
    rental: 'Mietwagen',
    public: 'Öffentlich',
    taxi: 'Taxi',
    avgCarRental: 'Durchschn. Mietwagen',
    day: 'Tag',
    gasPrice: 'Benzinpreis',
    publicTransport: 'Öffentlicher Verkehr',
    holidays: 'Feiertage',
    noUpcomingHolidays: 'Keine bevorstehenden Feiertage gefunden',
    accommodationMap: 'Unterkunftskarte'
  },
  it: {
    back: 'Indietro',
    traveler: 'viaggiatore',
    travelers: 'viaggiatori',
    timeZone: 'Fuso Orario',
    yourTime: 'La Tua Ora',
    currency: 'Valuta',
    liveRate: 'Tasso live',
    airport: 'Aeroporto',
    primaryAirport: 'Aeroporto Principale',
    distance: 'Distanza',
    travelTime: 'Tempo di Viaggio',
    options: 'Opzioni',
    variable: 'Variabile',
    multipleOptions: 'Opzioni multiple',
    visaEntry: 'Visto e Ingresso',
    visaFreeEntry: 'Ingresso senza visto',
    forUSPassport: 'Per portatori di passaporto americano',
    maxStay: 'Soggiorno massimo',
    days: 'giorni',
    passportValidity: 'Validità passaporto',
    monthsMin: 'mesi min',
    yellowFever: 'Febbre gialla',
    vaccinationRecommended: 'Vaccinazione raccomandata',
    viewRequirements: 'Visualizza Requisiti',
    weatherIntel: 'Intel Meteo',
    transport: 'Trasporto',
    rental: 'Noleggio',
    public: 'Pubblico',
    taxi: 'Taxi',
    avgCarRental: 'Noleggio auto medio',
    day: 'giorno',
    gasPrice: 'Prezzo benzina',
    publicTransport: 'Trasporto pubblico',
    holidays: 'Festività',
    noUpcomingHolidays: 'Nessuna festività imminente trovata',
    accommodationMap: 'Mappa Alloggi'
  },
  pt: {
    back: 'Voltar',
    traveler: 'viajante',
    travelers: 'viajantes',
    timeZone: 'Fuso Horário',
    yourTime: 'Sua Hora',
    currency: 'Moeda',
    liveRate: 'Taxa ao vivo',
    airport: 'Aeroporto',
    primaryAirport: 'Aeroporto Principal',
    distance: 'Distância',
    travelTime: 'Tempo de Viagem',
    options: 'Opções',
    variable: 'Variável',
    multipleOptions: 'Múltiplas opções',
    visaEntry: 'Visto e Entrada',
    visaFreeEntry: 'Entrada sem visto',
    forUSPassport: 'Para portadores de passaporte americano',
    maxStay: 'Estadia máxima',
    days: 'dias',
    passportValidity: 'Validade do passaporte',
    monthsMin: 'meses mín',
    yellowFever: 'Febre amarela',
    vaccinationRecommended: 'Vacinação recomendada',
    viewRequirements: 'Ver Requisitos',
    weatherIntel: 'Intel do Clima',
    transport: 'Transporte',
    rental: 'Aluguel',
    public: 'Público',
    taxi: 'Táxi',
    avgCarRental: 'Aluguel médio de carro',
    day: 'dia',
    gasPrice: 'Preço da gasolina',
    publicTransport: 'Transporte público',
    holidays: 'Feriados',
    noUpcomingHolidays: 'Nenhum feriado próximo encontrado',
    accommodationMap: 'Mapa de Acomodação'
  },
  ru: {
    back: 'Назад',
    traveler: 'путешественник',
    travelers: 'путешественники',
    timeZone: 'Часовой Пояс',
    yourTime: 'Ваше Время',
    currency: 'Валюта',
    liveRate: 'Текущий курс',
    airport: 'Аэропорт',
    primaryAirport: 'Основной Аэропорт',
    distance: 'Расстояние',
    travelTime: 'Время в Пути',
    options: 'Варианты',
    variable: 'Переменная',
    multipleOptions: 'Несколько вариантов',
    visaEntry: 'Виза и Въезд',
    visaFreeEntry: 'Безвизовый въезд',
    forUSPassport: 'Для владельцев американского паспорта',
    maxStay: 'Макс. пребывание',
    days: 'дней',
    passportValidity: 'Действительность паспорта',
    monthsMin: 'мес. мин',
    yellowFever: 'Желтая лихорадка',
    vaccinationRecommended: 'Рекомендуется вакцинация',
    viewRequirements: 'Посмотреть Требования',
    weatherIntel: 'Погодная Информация',
    transport: 'Транспорт',
    rental: 'Аренда',
    public: 'Общественный',
    taxi: 'Такси',
    avgCarRental: 'Средняя аренда авто',
    day: 'день',
    gasPrice: 'Цена бензина',
    publicTransport: 'Общественный транспорт',
    holidays: 'Праздники',
    noUpcomingHolidays: 'Предстоящих праздников не найдено',
    accommodationMap: 'Карта Размещения'
  },
  ja: {
    back: '戻る',
    traveler: '旅行者',
    travelers: '旅行者',
    timeZone: 'タイムゾーン',
    yourTime: 'あなたの時間',
    currency: '通貨',
    liveRate: 'リアルタイムレート',
    airport: '空港',
    primaryAirport: '主要空港',
    distance: '距離',
    travelTime: '移動時間',
    options: 'オプション',
    variable: '変数',
    multipleOptions: '複数のオプション',
    visaEntry: 'ビザと入国',
    visaFreeEntry: 'ビザなし入国',
    forUSPassport: 'アメリカのパスポート所持者向け',
    maxStay: '最大滞在',
    days: '日',
    passportValidity: 'パスポートの有効性',
    monthsMin: 'ヶ月最小',
    yellowFever: '黄熱病',
    vaccinationRecommended: 'ワクチン接種推奨',
    viewRequirements: '要件を表示',
    weatherIntel: '天気情報',
    transport: '交通',
    rental: 'レンタル',
    public: '公共',
    taxi: 'タクシー',
    avgCarRental: '平均レンタカー',
    day: '日',
    gasPrice: 'ガソリン価格',
    publicTransport: '公共交通機関',
    holidays: '祝日',
    noUpcomingHolidays: '今後の祝日が見つかりません',
    accommodationMap: '宿泊施設マップ'
  },
  ko: {
    back: '뒤로',
    traveler: '여행자',
    travelers: '여행자들',
    timeZone: '시간대',
    yourTime: '귀하의 시간',
    currency: '통화',
    liveRate: '실시간 환율',
    airport: '공항',
    primaryAirport: '주요 공항',
    distance: '거리',
    travelTime: '이동 시간',
    options: '옵션',
    variable: '변수',
    multipleOptions: '여러 옵션',
    visaEntry: '비자 및 입국',
    visaFreeEntry: '무비자 입국',
    forUSPassport: '미국 여권 소지자 대상',
    maxStay: '최대 체류',
    days: '일',
    passportValidity: '여권 유효성',
    monthsMin: '개월 최소',
    yellowFever: '황열병',
    vaccinationRecommended: '예방접종 권장',
    viewRequirements: '요구사항 보기',
    weatherIntel: '날씨 정보',
    transport: '교통',
    rental: '렌탈',
    public: '공공',
    taxi: '택시',
    avgCarRental: '평균 렌터카',
    day: '일',
    gasPrice: '기름값',
    publicTransport: '대중교통',
    holidays: '휴일',
    noUpcomingHolidays: '다가오는 휴일을 찾을 수 없음',
    accommodationMap: '숙박 시설 지도'
  },
  zh: {
    back: '返回',
    traveler: '旅行者',
    travelers: '旅行者',
    timeZone: '时区',
    yourTime: '您的时间',
    currency: '货币',
    liveRate: '实时汇率',
    airport: '机场',
    primaryAirport: '主要机场',
    distance: '距离',
    travelTime: '旅行时间',
    options: '选项',
    variable: '变量',
    multipleOptions: '多个选项',
    visaEntry: '签证和入境',
    visaFreeEntry: '免签入境',
    forUSPassport: '美国护照持有者',
    maxStay: '最大停留',
    days: '天',
    passportValidity: '护照有效期',
    monthsMin: '个月最少',
    yellowFever: '黄热病',
    vaccinationRecommended: '建议接种疫苗',
    viewRequirements: '查看要求',
    weatherIntel: '天气信息',
    transport: '交通',
    rental: '租赁',
    public: '公共',
    taxi: '出租车',
    avgCarRental: '平均租车',
    day: '天',
    gasPrice: '汽油价格',
    publicTransport: '公共交通',
    holidays: '假期',
    noUpcomingHolidays: '未找到即将到来的假期',
    accommodationMap: '住宿地图'
  }
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<Language>('en');

  const t = translations[language];

  return {
    language,
    setLanguage,
    t
  };
};
