// Step 7.5 — Airline catalog.
//
// Selected airlines persist as IATA codes in users.airlines (per the column
// comment "up to 3 preferred airline codes, e.g. AA, UA"); `name` is display-
// only. Shared between AirlineStep (renders the picker) and CompleteStep
// (maps stored codes back to names for the recap).
//
// Generated once from the `airline-codes` npm package (npow/airline-codes),
// which itself wraps the OpenFlights.org open airline database — the
// standard free/open reference dataset for this kind of data, cited across
// many aviation and travel-tech projects. Not hand-typed: filtered from the
// raw ~6,162 records to active === 'Y' with a valid IATA code and no
// "cargo"/"freight" in the name (954 entries) — a mechanical filter, not a
// hand-picked allowlist, so it won't silently drift incomplete the way the
// old 18-airline list did.
//
// Known caveat: OpenFlights' snapshot predates some airline rebrands/mergers
// that reused an existing IATA code, so two entries are explicitly corrected
// here rather than trusted as-is: AZ (was "Alitalia", defunct since 2021 →
// "ITA Airways") and LA (was "LAN Airlines", merged into LATAM in 2012 →
// "LATAM") — both already correct in the prior hand-typed list, carried
// forward as overrides rather than reverted. The dataset also still includes
// some very small/informal operators at the tail (e.g. air-taxi outfits) —
// left in rather than further hand-filtered, since they're honest entries
// from the source, not something to silently prune by name-guessing.
//
// Regenerate by rerunning that filter (+ the two overrides) against a fresh
// install of the package if the airline list ever needs updating.

export interface Airline {
  /** IATA code — the stored value (users.airlines text[]). */
  code: string;
  /** Display name (chips, recap). */
  name: string;
}

export const AIRLINES: Airline[] = [
  { code: "12", name: "12 North" },
  { code: "1T", name: "1Time Airline" },
  { code: "Q5", name: "40-Mile Air" },
  { code: "47", name: "88" },
  { code: "1B", name: "Abacus International" },
  { code: "M3", name: "ABSA - Aerolinhas Brasileiras" },
  { code: "MO", name: "Abu Dhabi Amiri Flight" },
  { code: "ZY", name: "Ada Air" },
  { code: "KI", name: "Adam Air" },
  { code: "JP", name: "Adria Airways" },
  { code: "A3", name: "Aegean Airlines" },
  { code: "RE", name: "Aer Arann" },
  { code: "EI", name: "Aer Lingus" },
  { code: "JY", name: "Aereonautica militare" },
  { code: "EM", name: "Aero Benin" },
  { code: "Q6", name: "Aero Condor Peru" },
  { code: "AJ", name: "Aero Contractors" },
  { code: "GV", name: "Aero Flight" },
  { code: "QL", name: "Aero Lanka" },
  { code: "2D", name: "Aero VIP (2D)" },
  { code: "BF", name: "Aero-Service" },
  { code: "2B", name: "Aerocondor" },
  { code: "SU", name: "Aeroflot Russian Airlines" },
  { code: "D9", name: "Aeroflot-Don" },
  { code: "5N", name: "Aeroflot-Nord" },
  { code: "XL", name: "Aerolane" },
  { code: "7E", name: "Aeroline GmbH" },
  { code: "AR", name: "Aerolineas Argentinas" },
  { code: "2K", name: "Aerolineas Galapagos (Aerogal)" },
  { code: "5D", name: "Aerolitoral" },
  { code: "VW", name: "Aeromar" },
  { code: "AM", name: "AeroMéxico" },
  { code: "OT", name: "Aeropelican Air Services" },
  { code: "PL", name: "Aeroper" },
  { code: "P5", name: "AeroRep" },
  { code: "5L", name: "Aerosur" },
  { code: "VV", name: "Aerosvit Airlines" },
  { code: "W4", name: "AeroWorld " },
  { code: "FK", name: "Africa West" },
  { code: "8U", name: "Afriqiyah Airways" },
  { code: "ZI", name: "Aigle Azur" },
  { code: "RK", name: "Air Afrique" },
  { code: "AH", name: "Air Algerie" },
  { code: "A6", name: "Air Alps Aviation (A6)" },
  { code: "3S", name: "Air Antilles Express" },
  { code: "G9", name: "Air Arabia" },
  { code: "E5", name: "Air Arabia Egypt" },
  { code: "3O", name: "Air Arabia Maroc" },
  { code: "KC", name: "Air Astana" },
  { code: "CC", name: "Air Atlanta Icelandic" },
  { code: "UU", name: "Air Austral" },
  { code: "W9", name: "Air Bagan" },
  { code: "BT", name: "Air Baltic" },
  { code: "AB", name: "Air Berlin" },
  { code: "JA", name: "Air Bosna" },
  { code: "BP", name: "Air Botswana" },
  { code: "2J", name: "Air Burkina" },
  { code: "BX", name: "Air Busan" },
  { code: "SB", name: "Air Caledonie International" },
  { code: "AC", name: "Air Canada" },
  { code: "QK", name: "Air Canada Jazz" },
  { code: "TX", name: "Air Caraïbes" },
  { code: "2S", name: "Air Carnival" },
  { code: "CV", name: "Air Chathams" },
  { code: "CA", name: "Air China" },
  { code: "3E", name: "Air Choice One" },
  { code: "3I", name: "Air Comet Chile" },
  { code: "LB", name: "Air Costa" },
  { code: "EN", name: "Air Dolomiti" },
  { code: "UX", name: "Air Europa" },
  { code: "PE", name: "Air Europe" },
  { code: "OF", name: "Air Finland" },
  { code: "QH", name: "Air Florida" },
  { code: "GS", name: "Air Foyle" },
  { code: "AF", name: "Air France" },
  { code: "7T", name: "Air Glaciers" },
  { code: "GL", name: "Air Greenland" },
  { code: "2U", name: "Air Guinee Express" },
  { code: "GG", name: "Air Guyane" },
  { code: "HH", name: "Air Hamburg (AHO)" },
  { code: "NY", name: "Air Iceland" },
  { code: "IX", name: "Air India Express" },
  { code: "AI", name: "Air India Limited" },
  { code: "CD", name: "Air India Regional" },
  { code: "PP", name: "Air Indus" },
  { code: "VU", name: "Air Ivoire" },
  { code: "JM", name: "Air Jamaica" },
  { code: "NQ", name: "Air Japan" },
  { code: "9Y", name: "Air Kazakhstan" },
  { code: "QP", name: "Air Kenya (Priv)" },
  { code: "4A", name: "Air Kiribati" },
  { code: "JS", name: "Air Koryo" },
  { code: "VD", name: "Air Libert" },
  { code: "LT", name: "Air Lituanica" },
  { code: "LK", name: "Air Luxor" },
  { code: "NX", name: "Air Macau" },
  { code: "MD", name: "Air Madagascar" },
  { code: "NM", name: "Air Madrid" },
  { code: "QM", name: "Air Malawi" },
  { code: "KM", name: "Air Malta" },
  { code: "6T", name: "Air Mandalay" },
  { code: "CW", name: "Air Marshall Islands" },
  { code: "MK", name: "Air Mauritius" },
  { code: "DR", name: "Air Mediterranee" },
  { code: "P8", name: "Air Mekong" },
  { code: "9U", name: "Air Moldova" },
  { code: "TM", name: "Air Mozambique" },
  { code: "SW", name: "Air Namibia" },
  { code: "NZ", name: "Air New Zealand" },
  { code: "EL", name: "Air Nippon" },
  { code: "PX", name: "Air Niugini" },
  { code: "4N", name: "Air North Charter - Canada" },
  { code: "YW", name: "Air Nostrum" },
  { code: "AP", name: "Air One" },
  { code: "FJ", name: "Air Pacific" },
  { code: "OP", name: "Air Pegasus" },
  { code: "2P", name: "Air Philippines" },
  { code: "A7", name: "Air Plus Comet" },
  { code: "GZ", name: "Air Rarotonga" },
  { code: "S2", name: "Air Sahara" },
  { code: "PJ", name: "Air Saint Pierre" },
  { code: "2O", name: "Air Salone" },
  { code: "20", name: "Air Salone" },
  { code: "JU", name: "Air Serbia" },
  { code: "HM", name: "Air Seychelles" },
  { code: "BM", name: "Air Sicilia" },
  { code: "4D", name: "Air Sinai" },
  { code: "VT", name: "Air Tahiti" },
  { code: "TN", name: "Air Tahiti Nui" },
  { code: "TC", name: "Air Tanzania" },
  { code: "8T", name: "Air Tindi" },
  { code: "TS", name: "Air Transat" },
  { code: "NF", name: "Air Vanuatu" },
  { code: "VL", name: "Air VIA" },
  { code: "UK", name: "Air Vistara" },
  { code: "G6", name: "Air Volga" },
  { code: "6G", name: "Air Wales" },
  { code: "ZW", name: "Air Wisconsin" },
  { code: "UM", name: "Air Zimbabwe" },
  { code: "F8", name: "Air2there" },
  { code: "AK", name: "AirAsia" },
  { code: "D7", name: "AirAsia X" },
  { code: "ED", name: "Airblue" },
  { code: "R3", name: "Aircompany Yakutia" },
  { code: "4C", name: "Aires" },
  { code: "A5", name: "Airlinair" },
  { code: "FO", name: "Airlines Of Tasmania" },
  { code: "CG", name: "Airlines PNG" },
  { code: "4Z", name: "Airlink (SAA)" },
  { code: "TL", name: "Airnorth" },
  { code: "OG", name: "AirOnix" },
  { code: "R8", name: "AirRussia" },
  { code: "FL", name: "AirTran Airways" },
  { code: "NA", name: "Al-Naser Airlines" },
  { code: "J4", name: "ALAK" },
  { code: "AS", name: "Alaska Airlines" },
  { code: "KO", name: "Alaska Central Express" },
  { code: "J5", name: "Alaska Seaplane Service" },
  { code: "LV", name: "Albanian Airlines" },
  { code: "CT", name: "Alitalia Cityliner" },
  { code: "XM", name: "Alitalia Express" },
  { code: "9A", name: "All Africa" },
  { code: "A2", name: "All America" },
  { code: "2R", name: "All America AR" },
  { code: "0P", name: "All America BOPY" },
  { code: "1Y", name: "All America BR" },
  { code: "1R", name: "All America CL" },
  { code: "0Y", name: "All America CO" },
  { code: "0M", name: "All America MX" },
  { code: "AG", name: "All America US" },
  { code: "L1", name: "All Argentina" },
  { code: "Z0", name: "All Argentina Express" },
  { code: "L9", name: "All Asia" },
  { code: "88", name: "All Australia" },
  { code: "7O", name: "All Colombia" },
  { code: "N9", name: "All Europe" },
  { code: "NH", name: "All Nippon Airways" },
  { code: "N7", name: "All Spain" },
  { code: "G4", name: "Allegiant Air" },
  { code: "QQ", name: "Alliance Airlines" },
  { code: "UJ", name: "AlMasria Universal Airlines" },
  { code: "AQ", name: "Aloha Airlines" },
  { code: "6R", name: "Alrosa Mirny Air Enterprise" },
  { code: "Z8", name: "Amaszonas" },
  { code: "HP", name: "America West Airlines" },
  { code: "AA", name: "American Airlines" },
  { code: "MQ", name: "American Eagle Airlines" },
  { code: "WD", name: "Amsterdam Airlines" },
  { code: "AN", name: "Ansett Australia" },
  { code: "ZM", name: "Apache Air" },
  { code: "FG", name: "Ariana Afghan Airlines" },
  { code: "Q9", name: "Arik Niger" },
  { code: "OR", name: "Arkefly" },
  { code: "IZ", name: "Arkia Israel Airlines" },
  { code: "U8", name: "Armavia" },
  { code: "JW", name: "Arrow Air" },
  { code: "R7", name: "Aserca Airlines" },
  { code: "Y5", name: "Asia Wings" },
  { code: "6K", name: "Asian Spirit" },
  { code: "AW", name: "Asian Wings Airways" },
  { code: "OZ", name: "Asiana Airlines" },
  { code: "4K", name: "Askari Aviation" },
  { code: "8D", name: "Astair" },
  { code: "5W", name: "Astraeus" },
  { code: "OB", name: "Astrakhan Airlines" },
  { code: "8V", name: "Astral Aviation" },
  { code: "I3", name: "ATA Airlines (Iran)" },
  { code: "ZF", name: "Athens Airways" },
  { code: "A1", name: "Atifly" },
  { code: "RC", name: "Atlantic Airways" },
  { code: "EV", name: "Atlantic Southeast Airlines" },
  { code: "TD", name: "Atlantis European Airways" },
  { code: "5Y", name: "Atlas Air" },
  { code: "8A", name: "Atlas Blue" },
  { code: "KK", name: "Atlasjet" },
  { code: "IQ", name: "Augsburg Airways" },
  { code: "GR", name: "Aurigny Air Services" },
  { code: "W7", name: "Austral Brasil" },
  { code: "AU", name: "Austral Lineas Aereas" },
  { code: "OS", name: "Austrian Airlines" },
  { code: "U1", name: "Aviabus" },
  { code: "EC", name: "Avialeasing Aviation Company" },
  { code: "AV", name: "Avianca - Aerovias Nacionales de Colombia" },
  { code: "AO", name: "Avianova (Russia)" },
  { code: "Z3", name: "Avient Aviation" },
  { code: "U3", name: "Avies" },
  { code: "B0", name: "Aws express" },
  { code: "J2", name: "Azerbaijan Airlines" },
  { code: "AD", name: "Azul" },
  { code: "CJ", name: "BA CityFlyer" },
  { code: "UP", name: "Bahamasair" },
  { code: "BU", name: "Baikotovitchestrian Airlines " },
  { code: "LZ", name: "Balkan Bulgarian Airlines" },
  { code: "B1", name: "Baltic Air lines" },
  { code: "PG", name: "Bangkok Airways" },
  { code: "8N", name: "Barents AirLink" },
  { code: "5B", name: "Bassaka airlines" },
  { code: "JV", name: "Bearskin Lake Air Service" },
  { code: "4T", name: "Belair Airlines" },
  { code: "B2", name: "Belavia Belarusian Airlines" },
  { code: "CH", name: "Bemidji Airlines" },
  { code: "8E", name: "Bering Air" },
  { code: "J8", name: "Berjaya Air" },
  { code: "BG", name: "Biman Bangladesh Airlines" },
  { code: "NT", name: "Binter Canarias" },
  { code: "BZ", name: "Black Stallion Airways" },
  { code: "0B", name: "Blue Air" },
  { code: "BV", name: "Blue Panorama Airlines" },
  { code: "QW", name: "Blue Wings" },
  { code: "KF", name: "Blue1" },
  { code: "BD", name: "bmi" },
  { code: "WW", name: "bmibaby" },
  { code: "4B", name: "Boutique Air (Priv)" },
  { code: "5Q", name: "BQB Lineas Aereas" },
  { code: "GB", name: "BRAZIL AIR" },
  { code: "DB", name: "Brit Air" },
  { code: "BA", name: "British Airways" },
  { code: "KJ", name: "British Mediterranean Airways" },
  { code: "SN", name: "Brussels Airlines" },
  { code: "1K", name: "BudgetAir" },
  { code: "FB", name: "Bulgaria Air" },
  { code: "BQ", name: "Buquebus Líneas Aéreas" },
  { code: "4P", name: "Business Aviation" },
  { code: "8B", name: "BusinessAir" },
  { code: "XV", name: "BVI Airways" },
  { code: "XG", name: "Calima Aviacion" },
  { code: "QC", name: "Camair-co" },
  { code: "K6", name: "Cambodia Angkor Air (K6)" },
  { code: "CN", name: "Canadian National Airways" },
  { code: "5T", name: "Canadian North" },
  { code: "C2", name: "CanXplorer" },
  { code: "C1", name: "CanXpress" },
  { code: "9K", name: "Cape Air" },
  { code: "BW", name: "Caribbean Airlines" },
  { code: "KW", name: "Carnival Air Lines" },
  { code: "V3", name: "Carpatair" },
  { code: "RV", name: "Caspian Airlines" },
  { code: "CX", name: "Cathay Pacific" },
  { code: "OC", name: "Catovair" },
  { code: "NS", name: "Caucasus Airlines" },
  { code: "KX", name: "Cayman Airways" },
  { code: "1F", name: "CB Airways UK ( Interliging Flights )" },
  { code: "CB", name: "CCML Airlines" },
  { code: "5J", name: "Cebu Pacific" },
  { code: "C0", name: "Centralwings" },
  { code: "RP", name: "Chautauqua Airlines" },
  { code: "CI", name: "China Airlines" },
  { code: "MU", name: "China Eastern Airlines" },
  { code: "WH", name: "China Northwest Airlines (WH)" },
  { code: "CZ", name: "China Southern Airlines" },
  { code: "9C", name: "China SSS" },
  { code: "KN", name: "China United" },
  { code: "HR", name: "China United Airlines" },
  { code: "OQ", name: "Chongqing Airlines" },
  { code: "99", name: "Ciao Air" },
  { code: "YC", name: "Ciel Canadien" },
  { code: "QI", name: "Cimber Air" },
  { code: "C9", name: "Cirrus Airlines" },
  { code: "QG", name: "Citilink Indonesia" },
  { code: "CF", name: "City Airline" },
  { code: "E8", name: "City Airways" },
  { code: "WX", name: "CityJet" },
  { code: "QA", name: "Click (Mexicana)" },
  { code: "DQ", name: "Coastal Air" },
  { code: "9L", name: "Colgan Air" },
  { code: "OH", name: "Comair" },
  { code: "MN", name: "Comair" },
  { code: "C5", name: "CommutAir" },
  { code: "KR", name: "Comores Airlines" },
  { code: "E9", name: "Compagnie Africaine d\\\\'Aviation" },
  { code: "DE", name: "Condor Flugdienst" },
  { code: "XZ", name: "Congo Express" },
  { code: "6A", name: "Consorcio Aviaxsa" },
  { code: "CS", name: "Continental Micronesia" },
  { code: "V0", name: "Conviasa" },
  { code: "CM", name: "Copa Airlines" },
  { code: "0X", name: "Copenhagen Express" },
  { code: "SS", name: "Corsairfly" },
  { code: "XK", name: "Corse-Mediterranee" },
  { code: "OU", name: "Croatia Airlines" },
  { code: "CU", name: "Cubana de Aviación" },
  { code: "CY", name: "Cyprus Airways" },
  { code: "YK", name: "Cyprus Turkish Airlines" },
  { code: "OK", name: "Czech Airlines" },
  { code: "D3", name: "Daallo Airlines" },
  { code: "H8", name: "Dalavia" },
  { code: "DA", name: "Dana Air" },
  { code: "V5", name: "Danube Wings (V5)" },
  { code: "0D", name: "Darwin Airline" },
  { code: "DX", name: "DAT Danish Air Transport" },
  { code: "DI", name: "dba" },
  { code: "DL", name: "Delta Air Lines" },
  { code: "J7", name: "Denim Air " },
  { code: "DH", name: "Dennis Sky" },
  { code: "KP", name: "Dense Airways" },
  { code: "KZ", name: "Dense Connection" },
  { code: "2A", name: "Deutsche Bahn" },
  { code: "D8", name: "Djibouti Airlines" },
  { code: "QD", name: "Dobrolet" },
  { code: "D1", name: "Domenican Airlines" },
  { code: "DO", name: "Dominicana de Aviaci" },
  { code: "E3", name: "Domodedovo Airlines" },
  { code: "KA", name: "Dragonair" },
  { code: "KB", name: "Druk Air" },
  { code: "H7", name: "Eagle Air" },
  { code: "E2", name: "Eagle Atlantic Airlines" },
  { code: "QU", name: "East African" },
  { code: "ZE", name: "Eastar Jet" },
  { code: "T3", name: "Eastern Airways" },
  { code: "13", name: "Eastern Atlantic Virtual Airlines" },
  { code: "DK", name: "Eastland Air" },
  { code: "U2", name: "easyJet" },
  { code: "DS", name: "EasyJet (DS)" },
  { code: "WK", name: "Edelweiss Air" },
  { code: "MS", name: "Egyptair" },
  { code: "LY", name: "El Al Israel Airlines" },
  { code: "UZ", name: "El-Buraq Air Transport" },
  { code: "E4", name: "Elysian Airlines" },
  { code: "EK", name: "Emirates" },
  { code: "EU", name: "Empresa Ecuatoriana De Aviacion" },
  { code: "FA", name: "Epic Holiday" },
  { code: "7H", name: "Era Alaska" },
  { code: "B8", name: "Eritrean Airlines" },
  { code: "OV", name: "Estonian Air" },
  { code: "ET", name: "Ethiopian Airlines" },
  { code: "EY", name: "Etihad Airways" },
  { code: "RZ", name: "Euro Exec Express" },
  { code: "24", name: "Euro Jet" },
  { code: "UI", name: "Eurocypria Airlines" },
  { code: "GJ", name: "Eurofly Service" },
  { code: "4L", name: "Euroline" },
  { code: "K2", name: "Eurolot" },
  { code: "EX", name: "Europe Jet" },
  { code: "EA", name: "European Air Express" },
  { code: "ES", name: "EuropeSky" },
  { code: "EW", name: "Eurowings" },
  { code: "BR", name: "EVA Air" },
  { code: "EZ", name: "Evergreen International Airlines" },
  { code: "JN", name: "Excel Airways" },
  { code: "EO", name: "Express One International" },
  { code: "XE", name: "ExpressJet" },
  { code: "EF", name: "Far Eastern Air Transport" },
  { code: "FU", name: "Felix Airways" },
  { code: "AY", name: "Finnair" },
  { code: "FC", name: "Finncomm Airlines" },
  { code: "FY", name: "Firefly" },
  { code: "7F", name: "First Air" },
  { code: "DP", name: "First Choice Airways" },
  { code: "B5", name: "Flightline" },
  { code: "Z9", name: "Flightlink Tanzania" },
  { code: "RF", name: "Florida West International Airways" },
  { code: "6I", name: "Fly 6ix" },
  { code: "F1", name: "Fly Brasil" },
  { code: "3F", name: "Fly Colombia ( Interliging Flights )" },
  { code: "FZ", name: "Fly Dubai" },
  { code: "ER", name: "Fly Europa" },
  { code: "FF", name: "Fly France" },
  { code: "F5", name: "Fly One" },
  { code: "X5", name: "Fly Romania" },
  { code: "5H", name: "Fly540" },
  { code: "F7", name: "Flybaboo" },
  { code: "BE", name: "Flybe" },
  { code: "B4", name: "Flyglobespan" },
  { code: "FH", name: "FlyHigh Airlines Ireland (FH)" },
  { code: "TE", name: "FlyLal" },
  { code: "LF", name: "FlyNordic" },
  { code: "PO", name: "FlyPortugal" },
  { code: "FX", name: "FOX Linhas Aereas" },
  { code: "FP", name: "Freedom Air" },
  { code: "F9", name: "Frontier Airlines" },
  { code: "2F", name: "Frontier Flying Service" },
  { code: "JH", name: "Fuji Dream Airlines" },
  { code: "GY", name: "Gabon Airlines" },
  { code: "GP", name: "Gadair European Airlines" },
  { code: "GA", name: "Garuda Indonesia" },
  { code: "4G", name: "Gazpromavia" },
  { code: "GT", name: "GB Airways" },
  { code: "GK", name: "Genesis" },
  { code: "A9", name: "Georgian Airways" },
  { code: "QB", name: "Georgian National Airlines" },
  { code: "GM", name: "German International Air Lines" },
  { code: "ST", name: "Germania" },
  { code: "4U", name: "Germanwings" },
  { code: "GX", name: "GermanXL" },
  { code: "G0", name: "Ghana International Airlines" },
  { code: "0G", name: "Global Airlines" },
  { code: "GH", name: "Globus" },
  { code: "GN", name: "GNB Linhas Aereas" },
  { code: "G8", name: "Go Air" },
  { code: "G7", name: "GoJet Airlines" },
  { code: "G3", name: "Gol Transportes Aéreos" },
  { code: "DC", name: "Golden Air" },
  { code: "YD", name: "Gomelavia" },
  { code: "ZK", name: "Great Lakes Airlines" },
  { code: "XX", name: "Greenfly" },
  { code: "TA", name: "Grupo TACA" },
  { code: "6P", name: "Gryphon Airlines" },
  { code: "GF", name: "Gulf Air Bahrain" },
  { code: "H6", name: "Hageland Aviation Services" },
  { code: "HU", name: "Hainan Airlines" },
  { code: "2T", name: "Haiti Ambassador Airlines" },
  { code: "7Z", name: "Halcyonair" },
  { code: "4R", name: "Hamburg International" },
  { code: "H1", name: "Hankook Air US" },
  { code: "HN", name: "Hankook Airline" },
  { code: "HF", name: "Hapagfly" },
  { code: "H3", name: "Harbour Air (Priv)" },
  { code: "HA", name: "Hawaiian Airlines" },
  { code: "BH", name: "Hawkair" },
  { code: "8H", name: "Heli France" },
  { code: "JB", name: "Helijet" },
  { code: "T4", name: "Hellas Jet" },
  { code: "HT", name: "Hellenic Imperial Airways" },
  { code: "HW", name: "Hello" },
  { code: "2L", name: "Helvetic Airways" },
  { code: "UD", name: "Hex'Air" },
  { code: "5K", name: "Hi Fly (5K)" },
  { code: "HC", name: "Himalayan Airlines" },
  { code: "HD", name: "Hokkaido International Airlines" },
  { code: "MR", name: "Homer Air" },
  { code: "HX", name: "Hong Kong Airlines" },
  { code: "UO", name: "Hong Kong Express Airways" },
  { code: "QX", name: "Horizon Air" },
  { code: "BN", name: "Horizon Airlines" },
  { code: "G5", name: "Huaxia" },
  { code: "H5", name: "I-Fly" },
  { code: "IB", name: "Iberia Airlines" },
  { code: "I2", name: "Iberia Express" },
  { code: "TY", name: "Iberworld" },
  { code: "FW", name: "Ibex Airlines" },
  { code: "FI", name: "Icelandair" },
  { code: "IK", name: "Imair Airlines" },
  { code: "Z5", name: "INAVIA Internacional" },
  { code: "IC", name: "Indian Airlines" },
  { code: "6E", name: "IndiGo Airlines" },
  { code: "QZ", name: "Indonesia AirAsia" },
  { code: "I5", name: "Indonesia Sky" },
  { code: "IO", name: "Indonesian Airlines" },
  { code: "G1", name: "Indya Airline Group" },
  { code: "7I", name: "Insel Air (7I/INC) (Priv)" },
  { code: "D6", name: "Interair South Africa" },
  { code: "4O", name: "Interjet (ABC Aerolineas)" },
  { code: "ID", name: "Interlink Airlines" },
  { code: "I4", name: "International AirLink" },
  { code: "9I", name: "International Europe" },
  { code: "3L", name: "Intersky" },
  { code: "IR", name: "Iran Air" },
  { code: "EP", name: "Iran Aseman Airlines" },
  { code: "IA", name: "Iraqi Airways" },
  { code: "WP", name: "Island Air (WP)" },
  { code: "IS", name: "Island Airlines" },
  { code: "1X", name: "Island Express Air" },
  { code: "IP", name: "Island Spirit" },
  { code: "IF", name: "Islas Airways" },
  { code: "WC", name: "Islena De Inversiones" },
  { code: "6H", name: "Israir" },
  { code: "AZ", name: "ITA Airways" },
  { code: "GI", name: "Itek Air" },
  { code: "I8", name: "IzAvia" },
  { code: "JC", name: "JAL Express" },
  { code: "JO", name: "JALways" },
  { code: "JD", name: "Japan Air System" },
  { code: "JL", name: "Japan Airlines" },
  { code: "EG", name: "Japan Asia Airways" },
  { code: "ZX", name: "Japan Regio" },
  { code: "NU", name: "Japan Transocean Air" },
  { code: "J9", name: "Jazeera Airways" },
  { code: "7C", name: "Jeju Air" },
  { code: "9W", name: "Jet Airways" },
  { code: "QJ", name: "Jet Airways" },
  { code: "LS", name: "Jet2.com" },
  { code: "8J", name: "Jet4You" },
  { code: "JF", name: "Jetairfly" },
  { code: "B6", name: "JetBlue Airways" },
  { code: "JG", name: "Jetgo Australia" },
  { code: "JQ", name: "Jetstar Airways" },
  { code: "3K", name: "Jetstar Asia Airways" },
  { code: "BL", name: "Jetstar Pacific" },
  { code: "NR", name: "Jettor Airlines" },
  { code: "LJ", name: "Jin Air" },
  { code: "3B", name: "JobAir" },
  { code: "JR", name: "Joy Air" },
  { code: "HO", name: "Juneyao Airlines" },
  { code: "JX", name: "Jusur airways" },
  { code: "RQ", name: "Kam Air" },
  { code: "KV", name: "Kavminvodyavia" },
  { code: "KD", name: "KD Avia" },
  { code: "M5", name: "Kenmore Air" },
  { code: "KQ", name: "Kenya Airways" },
  { code: "KH", name: "Kharkiv Airlines" },
  { code: "IT", name: "Kingfisher Airlines" },
  { code: "Y9", name: "Kish Air" },
  { code: "WA", name: "KLM Cityhopper" },
  { code: "KL", name: "KLM Royal Dutch Airlines" },
  { code: "7K", name: "Kogalymavia Air Company" },
  { code: "K7", name: "KoralBlue Airlines" },
  { code: "KE", name: "Korean Air" },
  { code: "ZC", name: "Korongo Airlines" },
  { code: "K1", name: "Kostromskie avialinii" },
  { code: "7B", name: "Krasnojarsky Airlines" },
  { code: "KY", name: "KSY" },
  { code: "GW", name: "Kuban Airlines" },
  { code: "KU", name: "Kuwait Airways" },
  { code: "MJ", name: "L" },
  { code: "LR", name: "LACSA" },
  { code: "4M", name: "LAN Argentina" },
  { code: "LU", name: "LAN Express" },
  { code: "LP", name: "LAN Peru" },
  { code: "QV", name: "Lao Airlines" },
  { code: "LA", name: "LATAM" },
  { code: "NG", name: "Lauda Air" },
  { code: "LQ", name: "LCM AIRLINES" },
  { code: "LI", name: "Leeward Islands Air Transport" },
  { code: "LE", name: "Liberty Airways" },
  { code: "LN", name: "Libyan Arab Airlines" },
  { code: "L8", name: "Line Blue" },
  { code: "LM", name: "Linhas A" },
  { code: "JT", name: "Lion Mentari Airlines" },
  { code: "C4", name: "LionXpress" },
  { code: "ZQ", name: "Locair" },
  { code: "LO", name: "LOT Polish Airlines" },
  { code: "PQ", name: "LSM Airlines" },
  { code: "YZ", name: "LSM AIRLINES " },
  { code: "II", name: "LSM International " },
  { code: "XO", name: "LTE International Airways" },
  { code: "L3", name: "LTU Austria" },
  { code: "L4", name: "Luchsh Airlines " },
  { code: "HE", name: "Luftfahrtgesellschaft Walter" },
  { code: "LH", name: "Lufthansa" },
  { code: "CL", name: "Lufthansa CityLine" },
  { code: "L5", name: "Lufttransport" },
  { code: "L7", name: "Lugansk Airlines" },
  { code: "LG", name: "Luxair" },
  { code: "W2", name: "Maastricht Airlines" },
  { code: "DM", name: "Maersk" },
  { code: "W5", name: "Mahan Air" },
  { code: "3W", name: "Malawian Airlines" },
  { code: "MH", name: "Malaysia Airlines" },
  { code: "Q2", name: "Maldivian" },
  { code: "ML", name: "Maldivo Airlines" },
  { code: "MA", name: "Malév" },
  { code: "OD", name: "Malindo Air" },
  { code: "R5", name: "Malta Air Charter" },
  { code: "RI", name: "Mandala Airlines" },
  { code: "AE", name: "Mandarin Airlines" },
  { code: "JE", name: "Mango" },
  { code: "MP", name: "Martinair" },
  { code: "Y8", name: "Marusya Airways" },
  { code: "M1", name: "Maryland Air" },
  { code: "M4", name: "Marysya Airlines" },
  { code: "M7", name: "MasAir" },
  { code: "6F", name: "MAT Airways" },
  { code: "IN", name: "MAT Macedonian Airlines" },
  { code: "L6", name: "Mauritania Airlines International" },
  { code: "MW", name: "Maya Island Air" },
  { code: "9H", name: "MDLR Airlines" },
  { code: "7Y", name: "Med Airways" },
  { code: "IG", name: "Meridiana" },
  { code: "MZ", name: "Merpati Nusantara Airlines" },
  { code: "YV", name: "Mesa Airlines" },
  { code: "XJ", name: "Mesaba Airlines" },
  { code: "7P", name: "Metro Batavia" },
  { code: "MX", name: "Mexicana de Aviaci" },
  { code: "I6", name: "MexicanaLink" },
  { code: "M2", name: "MHS Aviation GmbH" },
  { code: "OM", name: "MIAT Mongolian Airlines" },
  { code: "DF", name: "Michael Airlines" },
  { code: "ME", name: "Middle East Airlines" },
  { code: "JI", name: "Midway Airlines" },
  { code: "YX", name: "Midwest Airlines" },
  { code: "MY", name: "Midwest Airlines (Egypt)" },
  { code: "MB", name: "MNG Airlines" },
  { code: "2M", name: "Moldavian Airlines" },
  { code: "7M", name: "Mongolian International Air Lines " },
  { code: "YM", name: "Montenegro Airlines" },
  { code: "3R", name: "Moskovia Airlines" },
  { code: "M9", name: "Motor Sich" },
  { code: "UB", name: "Myanma Airways" },
  { code: "VZ", name: "MyTravel Airways" },
  { code: "8I", name: "Myway Airlines" },
  { code: "N1", name: "N1" },
  { code: "XY", name: "Nas Air" },
  { code: "UE", name: "Nasair" },
  { code: "NC", name: "National Jet Systems" },
  { code: "CE", name: "Nationwide Airlines" },
  { code: "ON", name: "Nauru Air Corporation" },
  { code: "RA", name: "Nepal Airlines" },
  { code: "1I", name: "NetJets" },
  { code: "EJ", name: "New England Airlines" },
  { code: "XB", name: "NEXT Brasil" },
  { code: "2N", name: "NextJet" },
  { code: "HG", name: "Niki" },
  { code: "NP", name: "Nile Air" },
  { code: "DD", name: "Nok Air" },
  { code: "NJ", name: "Nordic Global Airlines" },
  { code: "EE", name: "Nordica" },
  { code: "Y7", name: "NordStar Airlines" },
  { code: "N0", name: "Norte Lineas Aereas" },
  { code: "U7", name: "Northern Dene Airways" },
  { code: "NW", name: "Northwest Airlines" },
  { code: "J3", name: "Northwestern Air" },
  { code: "DY", name: "Norwegian Air Shuttle" },
  { code: "DU", name: "Norwegian Long Haul AS" },
  { code: "BJ", name: "Nouvel Air Tunisie" },
  { code: "O8", name: "Oasis Hong Kong Airlines" },
  { code: "O6", name: "Oceanair" },
  { code: "O2", name: "Oceanic Airlines" },
  { code: "OA", name: "Olympic Airlines" },
  { code: "WY", name: "Oman Air" },
  { code: "OY", name: "Omni Air International" },
  { code: "1C", name: "OneChina" },
  { code: "J1", name: "OneJet" },
  { code: "O1", name: "Orbit Airlines Azerbaijan" },
  { code: "OI", name: "Orchid Airlines" },
  { code: "R2", name: "Orenburg Airlines" },
  { code: "OX", name: "Orient Thai Airlines" },
  { code: "QO", name: "Origin Pacific Airways" },
  { code: "OL", name: "Ostfriesische Lufttransport" },
  { code: "OJ", name: "Overland Airways" },
  { code: "O7", name: "Ozjet Airlines" },
  { code: "8P", name: "Pacific Coastal Airline" },
  { code: "LW", name: "Pacific Wings" },
  { code: "PK", name: "Pakistan International Airlines" },
  { code: "5P", name: "Pal airlines" },
  { code: "PV", name: "PAN Air" },
  { code: "7Q", name: "Pan Am World Airways Dominicana" },
  { code: "WQ", name: "PanAm World Airways" },
  { code: "HI", name: "Papillon Grand Canyon Helicopters" },
  { code: "I7", name: "Paramount Airways" },
  { code: "PA", name: "Parmiss Airlines (IPV)" },
  { code: "P4", name: "Patriot Airways" },
  { code: "9Q", name: "PB Air" },
  { code: "MM", name: "Peach Aviation" },
  { code: "PC", name: "Pegasus Airlines" },
  { code: "H9", name: "PEGASUS AIRLINES-" },
  { code: "6D", name: "Pelita" },
  { code: "KS", name: "Peninsula Airways" },
  { code: "P9", name: "Peruvian Airlines" },
  { code: "PR", name: "Philippine Airlines" },
  { code: "PI", name: "Piedmont Airlines (1948-1989)" },
  { code: "9E", name: "Pinnacle Airlines" },
  { code: "PU", name: "PLUNA" },
  { code: "U4", name: "PMTair" },
  { code: "YQ", name: "Polet Airlines (Priv)" },
  { code: "PH", name: "Polynesian Airlines" },
  { code: "PD", name: "Porter Airlines" },
  { code: "NI", name: "Portugalia" },
  { code: "BK", name: "Potomac Air" },
  { code: "PW", name: "Precision Air" },
  { code: "PF", name: "Primera Air" },
  { code: "P0", name: "Proflight Commuter Services" },
  { code: "QF", name: "Qantas" },
  { code: "QR", name: "Qatar Airways" },
  { code: "R6", name: "RACSA" },
  { code: "RN", name: "Rainbow Air (RAI)" },
  { code: "RY", name: "Rainbow Air Canada" },
  { code: "RU", name: "Rainbow Air Euro" },
  { code: "RM", name: "Rainbow Air US" },
  { code: "RT", name: "Real Tonga" },
  { code: "PT", name: "Red Jet Andes" },
  { code: "QY", name: "Red Jet Canada" },
  { code: "4X", name: "Red Jet Mexico" },
  { code: "WZ", name: "Red Wings" },
  { code: "Z7", name: "REDjet" },
  { code: "YS", name: "Régional" },
  { code: "9N", name: "Regional Air Iceland" },
  { code: "FN", name: "Regional Airlines" },
  { code: "ZL", name: "Regional Express" },
  { code: "P7", name: "Regional Paraguaya" },
  { code: "9J", name: "Regionalia Chile" },
  { code: "N4", name: "Regionalia México" },
  { code: "2X", name: "Regionalia Uruguay" },
  { code: "9X", name: "Regionalia Venezuela" },
  { code: "RW", name: "Republic Airlines" },
  { code: "RR", name: "REXAIR VIRTUEL" },
  { code: "R4", name: "Rossiya" },
  { code: "FV", name: "Rossiya-Russian Airlines" },
  { code: "VJ", name: "Royal Air Cambodge" },
  { code: "AT", name: "Royal Air Maroc" },
  { code: "KG", name: "Royal Airways" },
  { code: "BI", name: "Royal Brunei Airlines" },
  { code: "69", name: "Royal European Airlines" },
  { code: "RL", name: "Royal Falcon" },
  { code: "RJ", name: "Royal Jordanian" },
  { code: "WB", name: "Rwandair Express" },
  { code: "RD", name: "Ryan International Airlines" },
  { code: "FR", name: "Ryanair" },
  { code: "S7", name: "S7 Airlines" },
  { code: "4Q", name: "Safi Airlines" },
  { code: "S6", name: "Salmon Air" },
  { code: "SO", name: "Salsa d\\\\'Haiti" },
  { code: "SZ", name: "Salzburg arrows" },
  { code: "ZS", name: "Sama Airlines" },
  { code: "S3", name: "Santa Barbara Airlines" },
  { code: "6W", name: "Saratov Aviation Division" },
  { code: "HZ", name: "Sat Airlines" },
  { code: "SP", name: "SATA Air Acores" },
  { code: "S4", name: "SATA International" },
  { code: "9R", name: "SATENA" },
  { code: "SV", name: "Saudi Arabian Airlines" },
  { code: "SK", name: "Scandinavian Airlines System" },
  { code: "DV", name: "Scat Air" },
  { code: "TZ", name: "Scoot" },
  { code: "BB", name: "Seaborne Airlines" },
  { code: "K5", name: "SeaPort Airlines" },
  { code: "DN", name: "Senegal Airlines" },
  { code: "YR", name: "SENIC AIRLINES" },
  { code: "S1", name: "Serbian Airlines" },
  { code: "FS", name: "Servicios de Transportes A" },
  { code: "D2", name: "Severstal Air Company" },
  { code: "5E", name: "SGA Airlines" },
  { code: "NL", name: "Shaheen Air International" },
  { code: "SC", name: "Shandong Airlines" },
  { code: "FM", name: "Shanghai Airlines" },
  { code: "SH", name: "Sharp Airlines" },
  { code: "ZH", name: "Shenzhen Airlines" },
  { code: "S5", name: "Shuttle America" },
  { code: "5M", name: "Sibaviatrans" },
  { code: "3U", name: "Sichuan Airlines" },
  { code: "FT", name: "Siem Reap Airways" },
  { code: "MI", name: "SilkAir" },
  { code: "3M", name: "Silver Airways (3M)" },
  { code: "SQ", name: "Singapore Airlines" },
  { code: "N5", name: "Skagway Air Service" },
  { code: "H2", name: "Sky Airline" },
  { code: "GQ", name: "Sky Express" },
  { code: "XW", name: "Sky Express" },
  { code: "RS", name: "Sky Regional" },
  { code: "C7", name: "Sky Wing Pacific" },
  { code: "Q7", name: "SkyBahamas Airlines" },
  { code: "NE", name: "SkyEurope" },
  { code: "BC", name: "Skymark Airlines" },
  { code: "SI", name: "Skynet Airlines" },
  { code: "6J", name: "Skynet Asia Airways" },
  { code: "5G", name: "Skyservice Airlines" },
  { code: "AL", name: "Skywalk Airlines" },
  { code: "JZ", name: "Skyways Express" },
  { code: "OO", name: "SkyWest" },
  { code: "XR", name: "Skywest Australia" },
  { code: "SX", name: "SkyWork Airlines " },
  { code: "6Y", name: "SmartLynx Airlines" },
  { code: "S8", name: "Snowbird Airlines" },
  { code: "CQ", name: "SOCHI AIR" },
  { code: "Q3", name: "SOCHI AIR CHATER" },
  { code: "Q4", name: "SOCHI AIR EXPRESS" },
  { code: "IE", name: "Solomon Airlines" },
  { code: "SA", name: "South African Airways" },
  { code: "DG", name: "South East Asian Airlines" },
  { code: "A4", name: "Southern Winds Airlines" },
  { code: "76", name: "Southjet" },
  { code: "77", name: "Southjet connect" },
  { code: "WN", name: "Southwest Airlines" },
  { code: "JK", name: "Spanair" },
  { code: "SG", name: "Spicejet" },
  { code: "S0", name: "Spike Airlines" },
  { code: "NK", name: "Spirit Airlines" },
  { code: "SM", name: "Spirit of Manila Airlines" },
  { code: "9S", name: "Spring Airlines" },
  { code: "IJ", name: "Spring Airlines Japan" },
  { code: "UL", name: "SriLankan Airlines" },
  { code: "SJ", name: "Sriwijaya Air" },
  { code: "7G", name: "Star Flyer" },
  { code: "2I", name: "Star Peru (2I)" },
  { code: "V9", name: "Star1 Airlines" },
  { code: "S9", name: "Starbow Airlines" },
  { code: "DZ", name: "Starline.kz" },
  { code: "NB", name: "Sterling Airlines" },
  { code: "8F", name: "STP Airways" },
  { code: "VC", name: "Strategic Airlines" },
  { code: "SD", name: "Sudan Airways" },
  { code: "SY", name: "Sun Country Airlines" },
  { code: "7L", name: "Sun D'Or" },
  { code: "XQ", name: "SunExpress" },
  { code: "WG", name: "Sunwing" },
  { code: "PY", name: "Surinam Airways" },
  { code: "7R", name: "Svyaz Rossiya" },
  { code: "WV", name: "Swe Fly" },
  { code: "LX", name: "Swiss International Air Lines" },
  { code: "RB", name: "Syrian Arab Airlines" },
  { code: "TJ", name: "T.J. Air" },
  { code: "DT", name: "TAAG Angola Airlines" },
  { code: "T0", name: "TACA Peru" },
  { code: "VR", name: "TACV" },
  { code: "7J", name: "Tajik Air" },
  { code: "JJ", name: "TAM Brazilian Airlines" },
  { code: "PZ", name: "TAM Mercosur" },
  { code: "EQ", name: "TAME" },
  { code: "QT", name: "TAMPA" },
  { code: "TP", name: "TAP Portugal" },
  { code: "RO", name: "Tarom" },
  { code: "U9", name: "Tatarstan Airlines" },
  { code: "TQ", name: "Texas Wings" },
  { code: "FD", name: "Thai AirAsia" },
  { code: "TG", name: "Thai Airways International" },
  { code: "SL", name: "Thai Lion Air" },
  { code: "WE", name: "Thai Smile Airways" },
  { code: "FQ", name: "Thomas Cook Airlines" },
  { code: "MT", name: "Thomas Cook Airlines" },
  { code: "BY", name: "Thomsonfly" },
  { code: "3P", name: "Tiara Air" },
  { code: "TT", name: "Tiger Airways Australia" },
  { code: "ZT", name: "Tomp Airlines" },
  { code: "T6", name: "Trans Pas Air" },
  { code: "AX", name: "Trans States Airlines" },
  { code: "UN", name: "Transaero Airlines" },
  { code: "GE", name: "TransAsia Airways" },
  { code: "TO", name: "Transavia France" },
  { code: "HV", name: "Transavia Holland" },
  { code: "TH", name: "TransBrasil Airlines" },
  { code: "TI", name: "TransHolding" },
  { code: "YO", name: "TransHolding System" },
  { code: "M8", name: "TransNusa Air" },
  { code: "1E", name: "TransRussiaAirlines" },
  { code: "9T", name: "Transwest Air" },
  { code: "TB", name: "TrasBrasil" },
  { code: "QS", name: "Travel Service" },
  { code: "8R", name: "TRIP Linhas A" },
  { code: "PM", name: "Tropic Air" },
  { code: "X3", name: "TUIfly" },
  { code: "11", name: "TUIfly (X3)" },
  { code: "6B", name: "TUIfly Nordic" },
  { code: "UG", name: "Tuninter" },
  { code: "TU", name: "Tunisair" },
  { code: "3T", name: "Turan Air" },
  { code: "TK", name: "Turkish Airlines" },
  { code: "T5", name: "Turkmenistan Airlines" },
  { code: "TW", name: "Tway Airlines" },
  { code: "T7", name: "Twin Jet" },
  { code: "VO", name: "Tyrolean Airways" },
  { code: "PS", name: "Ukraine International Airlines" },
  { code: "UF", name: "UM Airlines" },
  { code: "B7", name: "Uni Air" },
  { code: "UA", name: "United Airlines" },
  { code: "4H", name: "United Airways" },
  { code: "U6", name: "Ural Airlines" },
  { code: "US", name: "US Airways" },
  { code: "UH", name: "US Helicopter Corporation" },
  { code: "U5", name: "USA3000 Airlines" },
  { code: "UT", name: "UTair Aviation" },
  { code: "UR", name: "UTair-Express" },
  { code: "UW", name: "UVT Aero" },
  { code: "HY", name: "Uzbekistan Airways" },
  { code: "ZV", name: "V Air" },
  { code: "VF", name: "Valuair" },
  { code: "LC", name: "Varig Log" },
  { code: "VP", name: "VASP" },
  { code: "6V", name: "Via Conectia Airlines" },
  { code: "V1", name: "VIA Líneas Aéreas" },
  { code: "KT", name: "VickJet" },
  { code: "VN", name: "Vietnam Airlines" },
  { code: "VQ", name: "Viking Hellas" },
  { code: "NN", name: "VIM Airlines" },
  { code: "V6", name: "VIP Ecuador" },
  { code: "VX", name: "Virgin America" },
  { code: "VS", name: "Virgin Atlantic Airways" },
  { code: "VA", name: "Virgin Australia" },
  { code: "TV", name: "Virgin Express" },
  { code: "VK", name: "Virgin Nigeria Airways" },
  { code: "VH", name: "Virgin Pacific" },
  { code: "YY", name: "Virginwings" },
  { code: "V2", name: "Vision Airlines (V2)" },
  { code: "ZG", name: "Viva Macau" },
  { code: "5Z", name: "VivaColombia" },
  { code: "XF", name: "Vladivostok Air" },
  { code: "VG", name: "VLM Airlines" },
  { code: "8K", name: "Voestar" },
  { code: "VE", name: "Volare Airlines" },
  { code: "Y4", name: "Volaris" },
  { code: "N3", name: "Volaris El Salvador" },
  { code: "VI", name: "Volga-Dnepr Airlines" },
  { code: "V7", name: "VOLOTEA Airways" },
  { code: "9V", name: "Volotea Costa Rica" },
  { code: "RG", name: "VRG Linhas Aereas" },
  { code: "6C", name: "Vuela Cuba" },
  { code: "VY", name: "Vueling Airlines" },
  { code: "4S", name: "Vuola Italia" },
  { code: "7W", name: "Wayraper" },
  { code: "WJ", name: "WebJet Linhas A" },
  { code: "2W", name: "Welcome Air" },
  { code: "PN", name: "West Air China" },
  { code: "8O", name: "West Coast Air" },
  { code: "WS", name: "WestJet" },
  { code: "WR", name: "WestJet Encore" },
  { code: "WF", name: "Widerøe" },
  { code: "IV", name: "Wind Jet" },
  { code: "WM", name: "Windward Islands Airways" },
  { code: "IW", name: "Wings Air" },
  { code: "W6", name: "Wizz Air" },
  { code: "8Z", name: "Wizz Air Hungary" },
  { code: "WU", name: "Wizz Air Ukraine" },
  { code: "WO", name: "World Airways" },
  { code: "W1", name: "World Experience Airline" },
  { code: "W3", name: "World Scale Airlines" },
  { code: "XA", name: "XAIR USA" },
  { code: "MF", name: "Xiamen Airlines" },
  { code: "SE", name: "XL Airways France" },
  { code: "XN", name: "Xpressair" },
  { code: "XP", name: "XPTO" },
  { code: "YL", name: "Yamal Airlines" },
  { code: "HK", name: "Yangon Airways" },
  { code: "YH", name: "Yangon Airways Ltd." },
  { code: "Y1", name: "Yellowstone Club Private Shuttle" },
  { code: "YE", name: "Yellowtail" },
  { code: "IY", name: "Yemenia" },
  { code: "YT", name: "Yeti Airways" },
  { code: "3Q", name: "Yunnan Airlines" },
  { code: "Z6", name: "ZABAIKAL AIRLINES" },
  { code: "ZP", name: "Zabaykalskii Airlines" },
  { code: "ZJ", name: "Zambezi Airlines (ZMA)" },
  { code: "K8", name: "Zambia Skyways" },
  { code: "ZN", name: "Zenith International Airline" },
  { code: "Z2", name: "Zest Air" },
  { code: "Z4", name: "Zoom Airlines" },
  { code: "ZZ", name: "Zz" },
];

/** Friendly name for an IATA code; falls back to the code for unknown values. */
export const airlineName = (code: string): string =>
  AIRLINES.find((a) => a.code === code)?.name ?? code;
