// Utility to help migrate existing country names to ISO country codes
// This provides backward compatibility during the transition

export const countryNameToCode: { [key: string]: string } = {
    'United States': 'US',
    'United Kingdom': 'GB',
    'Canada': 'CA',
    'Australia': 'AU',
    'Germany': 'DE',
    'France': 'FR',
    'Japan': 'JP',
    'South Korea': 'KR',
    'Brazil': 'BR',
    'Mexico': 'MX',
    'India': 'IN',
    'China': 'CN',
    'Netherlands': 'NL',
    'Sweden': 'SE',
    'Norway': 'NO',
    'Denmark': 'DK',
    'Switzerland': 'CH',
    'Italy': 'IT',
    'Spain': 'ES',
    'Portugal': 'PT',
    'Belgium': 'BE',
    'Austria': 'AT',
    'Poland': 'PL',
    'Czech Republic': 'CZ',
    'Hungary': 'HU',
    'Romania': 'RO',
    'Bulgaria': 'BG',
    'Greece': 'GR',
    'Finland': 'FI',
    'Estonia': 'EE',
    'Latvia': 'LV',
    'Lithuania': 'LT',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Croatia': 'HR',
    'Serbia': 'RS',
    'Bosnia and Herzegovina': 'BA',
    'Montenegro': 'ME',
    'North Macedonia': 'MK',
    'Albania': 'AL',
    'Kosovo': 'XK',
    'Moldova': 'MD',
    'Ukraine': 'UA',
    'Belarus': 'BY',
    'Russia': 'RU',
    'Georgia': 'GE',
    'Armenia': 'AM',
    'Azerbaijan': 'AZ',
    'Turkey': 'TR',
    'Cyprus': 'CY',
    'Malta': 'MT',
    'Iceland': 'IS',
    'Ireland': 'IE',
    'Luxembourg': 'LU',
    'Monaco': 'MC',
    'Liechtenstein': 'LI',
    'San Marino': 'SM',
    'Vatican City': 'VA',
    'Andorra': 'AD',
    'New Zealand': 'NZ',
    'Fiji': 'FJ',
    'Papua New Guinea': 'PG',
    'Solomon Islands': 'SB',
    'Vanuatu': 'VU',
    'New Caledonia': 'NC',
    'French Polynesia': 'PF',
    'Samoa': 'WS',
    'Tonga': 'TO',
    'Tuvalu': 'TV',
    'Kiribati': 'KI',
    'Nauru': 'NR',
    'Palau': 'PW',
    'Marshall Islands': 'MH',
    'Micronesia': 'FM',
    'Northern Mariana Islands': 'MP',
    'Guam': 'GU',
    'American Samoa': 'AS',
    'Cook Islands': 'CK',
    'Niue': 'NU',
    'Tokelau': 'TK',
    'Pitcairn Islands': 'PN',
    'Easter Island': 'CL',
    'Galapagos Islands': 'EC',
    'Falkland Islands': 'FK',
    'South Georgia': 'GS',
    'Bouvet Island': 'BV',
    'Heard Island': 'HM',
    'French Southern Territories': 'TF',
    'British Indian Ocean Territory': 'IO',
    'Christmas Island': 'CX',
    'Cocos Islands': 'CC',
    'Norfolk Island': 'NF',
    'Ashmore and Cartier Islands': 'AU',
    'Coral Sea Islands': 'AU',
    'Lord Howe Island': 'AU',
    'Macquarie Island': 'AU',
    'Antarctica': 'AQ',
    'South Africa': 'ZA',
    'Egypt': 'EG',
    'Nigeria': 'NG',
    'Kenya': 'KE',
    'Ethiopia': 'ET',
    'Tanzania': 'TZ',
    'Uganda': 'UG',
    'Ghana': 'GH',
    'Morocco': 'MA',
    'Algeria': 'DZ',
    'Tunisia': 'TN',
    'Libya': 'LY',
    'Sudan': 'SD',
    'South Sudan': 'SS',
    'Chad': 'TD',
    'Niger': 'NE',
    'Mali': 'ML',
    'Burkina Faso': 'BF',
    'Senegal': 'SN',
    'Guinea': 'GN',
    'Guinea-Bissau': 'GW',
    'Sierra Leone': 'SL',
    'Liberia': 'LR',
    'Ivory Coast': 'CI',
    'Togo': 'TG',
    'Benin': 'BJ',
    'Cameroon': 'CM',
    'Central African Republic': 'CF',
    'Equatorial Guinea': 'GQ',
    'Gabon': 'GA',
    'Congo': 'CG',
    'Democratic Republic of the Congo': 'CD',
    'Angola': 'AO',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW',
    'Botswana': 'BW',
    'Namibia': 'NA',
    'Lesotho': 'LS',
    'Eswatini': 'SZ',
    'Madagascar': 'MG',
    'Comoros': 'KM',
    'Mauritius': 'MU',
    'Seychelles': 'SC',
    'Maldives': 'MV',
    'Sri Lanka': 'LK',
    'Bangladesh': 'BD',
    'Nepal': 'NP',
    'Bhutan': 'BT',
    'Myanmar': 'MM',
    'Laos': 'LA',
    'Cambodia': 'KH',
    'Vietnam': 'VN',
    'Malaysia': 'MY',
    'Indonesia': 'ID',
    'Philippines': 'PH',
    'Taiwan': 'TW',
    'Hong Kong': 'HK',
    'Macau': 'MO',
    'Mongolia': 'MN',
    'Kazakhstan': 'KZ',
    'Uzbekistan': 'UZ',
    'Kyrgyzstan': 'KG',
    'Tajikistan': 'TJ',
    'Turkmenistan': 'TM',
    'Afghanistan': 'AF',
    'Pakistan': 'PK',
    'Iran': 'IR',
    'Iraq': 'IQ',
    'Syria': 'SY',
    'Lebanon': 'LB',
    'Jordan': 'JO',
    'Israel': 'IL',
    'Palestine': 'PS',
    'Saudi Arabia': 'SA',
    'Yemen': 'YE',
    'Oman': 'OM',
    'UAE': 'AE',
    'United Arab Emirates': 'AE',
    'Qatar': 'QA',
    'Bahrain': 'BH',
    'Kuwait': 'KW',
    'Iraq': 'IQ',
    'Iran': 'IR',
    'Afghanistan': 'AF',
    'Pakistan': 'PK',
    'India': 'IN',
    'Nepal': 'NP',
    'Bhutan': 'BT',
    'Bangladesh': 'BD',
    'Myanmar': 'MM',
    'Thailand': 'TH',
    'Laos': 'LA',
    'Cambodia': 'KH',
    'Vietnam': 'VN',
    'Malaysia': 'MY',
    'Singapore': 'SG',
    'Indonesia': 'ID',
    'Philippines': 'PH',
    'Brunei': 'BN',
    'East Timor': 'TL',
    'Papua New Guinea': 'PG',
    'Fiji': 'FJ',
    'New Zealand': 'NZ',
    'Australia': 'AU',
    'Chile': 'CL',
    'Argentina': 'AR',
    'Uruguay': 'UY',
    'Paraguay': 'PY',
    'Bolivia': 'BO',
    'Peru': 'PE',
    'Ecuador': 'EC',
    'Colombia': 'CO',
    'Venezuela': 'VE',
    'Guyana': 'GY',
    'Suriname': 'SR',
    'French Guiana': 'GF',
    'Falkland Islands': 'FK',
    'South Georgia': 'GS',
    'Bouvet Island': 'BV',
    'Heard Island': 'HM',
    'French Southern Territories': 'TF',
    'British Indian Ocean Territory': 'IO',
    'Christmas Island': 'CX',
    'Cocos Islands': 'CC',
    'Norfolk Island': 'NF',
    'Ashmore and Cartier Islands': 'AU',
    'Coral Sea Islands': 'AU',
    'Lord Howe Island': 'AU',
    'Macquarie Island': 'AU',
    'Antarctica': 'AQ'
};

/**
 * Migrate a country name to its ISO country code
 * @param countryName - The full country name (e.g., "United States")
 * @returns The ISO country code (e.g., "US") or the original name if no match found
 */
export const migrateCountryNameToCode = (countryName: string): string => {
    return countryNameToCode[countryName] || countryName;
};

/**
 * Check if a string is a valid ISO country code
 * @param code - The string to check
 * @returns True if it's a valid 2-letter ISO country code
 */
export const isValidCountryCode = (code: string): boolean => {
    return /^[A-Z]{2}$/.test(code);
};

/**
 * Get a display name for a country code
 * @param countryCode - The ISO country code
 * @returns The country name or the original code if not found
 */
export const getCountryNameFromCode = (countryCode: string): string => {
    const entry = Object.entries(countryNameToCode).find(([_, code]) => code === countryCode);
    return entry ? entry[0] : countryCode;
};
