-- SUPERSEDED — intentional no-op.
--
-- Another repair re-attempt of the early visa_requirements table (old boolean
-- schema + stale "US -> Brazil visa-free" seed). Superseded by
-- 20260620185211_create_visa_requirements_cache.sql (Travel Buddy AI sync cache).
-- Body gutted so a fresh `db reset` no longer recreates the old schema/seed.
-- File + ledger entry retained on purpose — do not delete.
