-- SUPERSEDED — intentional no-op.
--
-- This migration originally created an early visa_requirements table (the
-- boolean visa_required schema) and seeded a now-STALE "US -> Brazil visa-free"
-- row — the original source of the visa data bug. It is fully superseded by
-- 20260620185211_create_visa_requirements_cache.sql, which DROPs and recreates
-- visa_requirements as the Travel Buddy AI sync cache.
--
-- The body is gutted so a fresh `db reset` no longer recreates the old schema or
-- the stale seed. The file + ledger entry are retained on purpose — do not delete
-- (deleting a ledger-applied migration breaks `db pull`/diffing).
