-- SUPERSEDED — intentional no-op.
--
-- This migration redefined public.users with auth_id as TEXT, which is wrong:
-- auth_id is uuid (the RLS policies use auth.uid() = auth_id, see
-- 20260331000000_enable_users_rls.sql). In practice it always no-opped — a
-- CREATE TABLE IF NOT EXISTS against the table already created by
-- 20250108000000_create_public_users_first.sql (the authoritative definition).
--
-- Body gutted to remove the auth_id type-conflict footgun. File + ledger entry
-- retained on purpose — do not delete.
